# goreleaser.yml
# Release automation
project_name: katzenpost
sign:
   artifacts: checksum
builds:
  # multiple builds defined as a yaml list
  -
    main: ./server/main.go
    binary: server
    flags: |
        -tags netgo -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH"
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
    goos:
      - linux
      - freebsd
      - netbsd
      - openbsd
      - darwin
    goarch:
      - arm64
      - amd64
  -
    main: ./authority/nonvoting/main.go
    binary: nonvoting-authority
    flags: |
        -tags netgo -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH"
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
    goos:
      - linux
      - freebsd
      - netbsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
  -
    main: ./authority/voting/main.go
    binary: voting-authority
    flags: |
        -tags netgo -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH"
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
    goos:
      - linux
      - freebsd
      - netbsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  wrap_in_directory: true
  files:
    - LICENSE
nfpm:
  vendor: Katzenpost Authors
  homepage: "https://katzenpost.mixnetworks.org/"
  maintainer: "irc://irc.oftc.net/#katzenpost"
  license: AGPL
  formats:
    - deb
    - rpm
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  github:
    owner: katzenpost
    name: daemons
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can change the name of the GitHub release.
  # Default is ``
  #  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false
