
[[constraint]]
  name = "github.com/katzenpost/channels"
  version = "0.0.1"

[[override]]
  version = "0.0.5"
  name = "github.com/katzenpost/minclient"

[[constraint]]
  name = "github.com/katzenpost/client"
  version = "0.0.2"

[[constraint]]
  name = "github.com/katzenpost/core"
  version = "0.0.7"

[[override]]
  version = "0.0.8"
  name = "github.com/katzenpost/authority"

[[constraint]]
  name = "github.com/katzenpost/doubleratchet"
  version = "0.0.0"

[[constraint]]
  name = "github.com/katzenpost/memspool"
  version = "0.0.1"

[[constraint]]
  name = "github.com/katzenpost/panda"
  version = "0.0.3"

# other stuff

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/abiosoft/ishell.v2"
  version = "2.0.0"

[[constraint]]
  name = "gopkg.in/op/go-logging.v1"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[prune]
  go-tests = true
  unused-packages = true